name: Build and deploy to stage server

on:
  pull_request:
    branches:
      - develop
    # types: [ closed ]

env:
  REGISTRY: ghcr.io
  REP_OWNER: b2b-marketplace-backend-team
  IMAGE_NAME: b2b_marketplace_backend
  DEPLOY_PATH: /b2b_marketplace

defaults:
  run:
    working-directory: .

jobs:
  buld_and_push_image_to_github_packages:
    name: Build and push image to GitHub Packages
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment:
      name: Stage

    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v3
      -
        name: Login to GutHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: infra/
          file: Dockerfile.stage
          labels: runnumber=${GITHUB_RUN_ID}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REP_OWNER }}/${{ env.IMAGE_NAME }}:stage,
            ${{ env.REGISTRY }}/${{ env.REP_OWNER }}/${{ env.IMAGE_NAME }}:latest,
            ${{ env.REGISTRY }}/${{ env.REP_OWNER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
